
name: Veille Chalons

on:
  schedule:
    - cron: "0 * * * *"   # toutes les heures
  workflow_dispatch:

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

permissions:
  contents: write

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install feedparser requests

      - name: Run script
        run: python scriptV.py
        env:
          WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }}

      - name: Commit seen.json
        run: |
          git config user.name "Koubiack666"
          git config user.email "koubiack666@gmail.com"
          git add seen.json
          git commit -m "update seen" || echo "No changes"
          git push
